### ISSUE TITLE
TypeScriptReact not working properly

### ISSUE THREAD

**Issue by hampustagerud** [ycm-core/ycmd#1377]
Hello! Thank you for your work on this project 🙏

I was very happy to see that #1336 was merged which would make it easier to do TS development in vim, however it does not seem to work. I have spent quite some time the last few days trying to get it to work but I am stuck.

I am editing the same `.tsx` file in the examples.

This is the resulting completion when the type is `typescriptreact` (default):
<img width="439" alt="Skärmavbild 2019-12-10 kl  20 48 37" src="https://user-images.githubusercontent.com/3395492/70563400-732f3100-1b8e-11ea-8ac6-dc64bd7cc27f.png">

If I force the filetype to `typescript` (`:set filetype=typescript`) I get the following:
<img width="446" alt="Skärmavbild 2019-12-10 kl  20 47 11" src="https://user-images.githubusercontent.com/3395492/70563275-3f540b80-1b8e-11ea-937f-34aefff2cb1e.png">

Another difference is that in the second example the completion appears instantly after I type `.` but in the first example I have to type a few characters.

Any ideas what it might be/how to solve this?

**Comment by bstaletic** [comment]
Hello. The first screenshot displays the completion candidates from the generic identifier completer. The second one is the actual tsserver response. Instead of making wild guesses, please open an issue in the ycm-core/YouCompleteMe repo and fill out the issue template as it will guide you how to provide all relevant debugging info.

**Comment by bstaletic** [comment]
Actually, forget what I said. I have figured it out.

You can get completions to work if you force them with `<C-Space>`, or if you configure the semantic triggers yourself. The problem is that there are no semantic triggers configured by default.

See:

https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/completer_utils.py#L228

There's `typescript`, but no `typescriptreact`.

Here's a patch, but with missing tests:

```diff
diff --git a/ycmd/completers/completer_utils.py b/ycmd/completers/completer_utils.py
index 9bf84e6f..f3d8184f 100644
--- a/ycmd/completers/completer_utils.py
+++ b/ycmd/completers/completer_utils.py
@@ -226,6 +226,7 @@ DEFAULT_FILETYPE_TRIGGERS = {
     'python,'
     'scala,'
     'typescript,'
+    'typescriptreact,'
     'vb' ) : [ '.' ],
   'ruby,rust' : [ '.', '::' ],
   'lua' : [ '.', ':' ],
```

**Comment by bstaletic** [comment]
#1378 should fix this.

**Comment by hampustagerud** [comment]
Thank you for the swift response! I'm sorry if this was not the correct repo but since this was the repo for the PR I assumed this was the place 🙂 

I have been digging some more but it's slow since I don't work in Python usually. I enabled the debug logging and got this stacktrace for `typescriptreact` (`typescript` prints no errors):

```
2019-12-11 10:22:41,070 - INFO - Received debug info request
2019-12-11 10:22:41,071 - ERROR - Error retrieving completer debug info
Traceback (most recent call last):
  File "~/.config/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 288, in DebugInfo
    request_data ).DebugInfo( request_data )
  File "~/.config/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 354, in _GetCompleterForRequestData
    return _server_state.GetFiletypeCompleter( request_data[ 'filetypes' ] )
  File "~/.config/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 100, in GetFiletypeCompleter
    current_filetypes ) )
ValueError: No semantic completer exists for filetypes: [u'typescriptreact']
```

I tried the PR branch and still get the same message, I have been looking through old issues and the documentation trying to find out why it doesn't recognize the filetype but no luck. I added a custom language server through the vim settings (unrelated to this repo but just FYI) and it started the server but does not get any completions. The logs are filled with:

```
2019-12-11 10:44:04,761 - DEBUG - RX: {'errors': [], 'completions': [], 'completion_start_column': 3}
```

after trying out with the test in the PR:

```
const a = { foo: 1 };

a.|
```

**Comment by bstaletic** [comment]
> ValueError: No semantic completer exists for filetypes: [u'typescriptreact']

This is a user error. You didn't update submodules. `git submodule update --init --recursive`.

**Comment by hampustagerud** [comment]
I did so not really but I'll keep looking at it 🙂 Thanks for your input

**Comment by bstaletic** [comment]
Oh, YCM didn't update the ycmd submodule. Go into `YouCompleteMe/third_party/ycmd` and pull the ycmd master. Either way, this is now a support request, not a bug. Use our gitter for that.

**Comment by hampustagerud** [comment]
Okay, thank you 🙂
